version: '3.5'

services:
  pets-webapi:
    image: maiznpetr/pets-webapi:v1
    volumes:
      - /docker-data/pets/logs/webapi/:/app/logs
    environment:
      - ConnectionStrings:Pets=Server=${SQL_URL:-pets-mariadb};Port=3306;Database=pets;User ID=root;Password=${SQL_ROOT_USER_PASSWORD};
      - ConnectionStrings:PetsMigration=Server=${SQL_URL:-pets-mariadb};Port=3306;Database=pets;User ID=root;Password=${SQL_ROOT_USER_PASSWORD};
    depends_on:
      - pets-mariadb
      - pets-proxy
    restart: always

  pets-client:
    image: maiznpetr/pets-client:v1
    depends_on:
      - pets-proxy
    restart: always

  pets-proxy:
    image: nginx:1.18.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/public.crt:/etc/nginx/public.crt
      - ./proxy/private.key:/etc/nginx/private.key
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /docker-data/pets/logs/proxy/:/var/log/nginx 
    depends_on:
      - pets-webapi
      - pets-client    
    restart: always


  pets-mariadb:
    image: mariadb:10.3.22
    ports:
       - "3306:3306"
    volumes:
      - /docker-data/pets/mariadb:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_USER_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
  #     - MYSQL_DATABASE=pets
    restart: always

volumes:
  pets-data:
    driver: local
